[package]
name = "mjsoc-attendance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4"
const_format = "0.2.31"
qrcode-generator = "4.1.9"
serde = { version = "1.0.188", features = ["derive"] }
